apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blog-service-bus
    release: blog-service-bus
  name: blog-service-bus
  namespace: dev-nodejs
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: blog-service-bus
      release: blog-service-bus
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blog-service-bus
        release: blog-service-bus
    spec:
      containers:
      - env:
        - name: sample-secret-1
          valueFrom:
            secretKeyRef:
              key: sample-secret-1
              name: devsecrets-nodejs
        image: enter-your-account.azurecr.io/enter-your-repository:build-tag
        imagePullPolicy: IfNotPresent
        name: nodejs
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 512m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 256Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      restartPolicy: Always
      securityContext: {}
